version: '2'
services:
  jenkins:
    build: .
    image: jenkins_ci:1.0.0
    container_name: jenkins_ci
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
