version: '2'
services:
    DB:
        image: postgres:10
        restart: always
        environment:
          POSTGRES_ROOT_PASSWORD: aLRz6aDf
          POSTGRES_DATABASE: clara_prod
          POSTGRES_USER: clara
          POSTGRES_PASSWORD: zT7xKX
        container_name: postgres_clara_prod
        volumes:
            - /data/db/prod:/var/lib/postgres

    adminer:
        image: adminer
        restart: always
        ports:
            - 8082:8080
        container_name: postgres_adminer_prod
