version: '2'
services:
    mongo:
        image: mongo:3.5
        command: --smallfiles --auth
        ports:
        - "27018:27017"
        container_name: mongo_clara_prod
        volumes:
        - /data/db/prod:/data/db
        restart: always