version: '2'
services:
    mongo:
        image: mongo:3.5
        command: --smallfiles #--auth
        ports:
        - "27017:27017"
        container_name: mongo_clara
        volumes:
        - /data/db:/data/db
        restart: always